// source: options/gorm.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_descriptor_pb = require('google-protobuf/google/protobuf/descriptor_pb.js');
goog.object.extend(proto, google_protobuf_descriptor_pb);
goog.exportSymbol('proto.gorm.AutoServerOptions', null, global);
goog.exportSymbol('proto.gorm.BelongsToOptions', null, global);
goog.exportSymbol('proto.gorm.ExtraField', null, global);
goog.exportSymbol('proto.gorm.GormFieldOptions', null, global);
goog.exportSymbol('proto.gorm.GormTag', null, global);
goog.exportSymbol('proto.gorm.HasManyOptions', null, global);
goog.exportSymbol('proto.gorm.HasOneOptions', null, global);
goog.exportSymbol('proto.gorm.ManyToManyOptions', null, global);
goog.exportSymbol('proto.gorm.MethodOptions', null, global);
goog.exportSymbol('proto.gorm.drop', null, global);
goog.exportSymbol('proto.gorm.includeList', null, global);
goog.exportSymbol('proto.gorm.method', null, global);
goog.exportSymbol('proto.gorm.ormable', null, global);
goog.exportSymbol('proto.gorm.server', null, global);
goog.exportSymbol('proto.gorm.table', null, global);
goog.exportSymbol('proto.gorm.tablePrefix', null, global);
goog.exportSymbol('proto.gorm.tag', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gorm.ExtraField = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gorm.ExtraField, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gorm.ExtraField.displayName = 'proto.gorm.ExtraField';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gorm.GormFieldOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gorm.GormFieldOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gorm.GormFieldOptions.displayName = 'proto.gorm.GormFieldOptions';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gorm.GormTag = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gorm.GormTag, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gorm.GormTag.displayName = 'proto.gorm.GormTag';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gorm.HasOneOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gorm.HasOneOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gorm.HasOneOptions.displayName = 'proto.gorm.HasOneOptions';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gorm.BelongsToOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gorm.BelongsToOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gorm.BelongsToOptions.displayName = 'proto.gorm.BelongsToOptions';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gorm.HasManyOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gorm.HasManyOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gorm.HasManyOptions.displayName = 'proto.gorm.HasManyOptions';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gorm.ManyToManyOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gorm.ManyToManyOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gorm.ManyToManyOptions.displayName = 'proto.gorm.ManyToManyOptions';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gorm.AutoServerOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gorm.AutoServerOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gorm.AutoServerOptions.displayName = 'proto.gorm.AutoServerOptions';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gorm.MethodOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gorm.MethodOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gorm.MethodOptions.displayName = 'proto.gorm.MethodOptions';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gorm.ExtraField.prototype.toObject = function(opt_includeInstance) {
  return proto.gorm.ExtraField.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gorm.ExtraField} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gorm.ExtraField.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    tag: jspb.Message.getFieldWithDefault(msg, 3, ""),
    pb_package: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gorm.ExtraField}
 */
proto.gorm.ExtraField.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gorm.ExtraField;
  return proto.gorm.ExtraField.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gorm.ExtraField} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gorm.ExtraField}
 */
proto.gorm.ExtraField.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTag(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPackage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gorm.ExtraField.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gorm.ExtraField.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gorm.ExtraField} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gorm.ExtraField.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTag();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPackage();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string type = 1;
 * @return {string}
 */
proto.gorm.ExtraField.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.ExtraField} returns this
 */
proto.gorm.ExtraField.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.gorm.ExtraField.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.ExtraField} returns this
 */
proto.gorm.ExtraField.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string tag = 3;
 * @return {string}
 */
proto.gorm.ExtraField.prototype.getTag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.ExtraField} returns this
 */
proto.gorm.ExtraField.prototype.setTag = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string package = 4;
 * @return {string}
 */
proto.gorm.ExtraField.prototype.getPackage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.ExtraField} returns this
 */
proto.gorm.ExtraField.prototype.setPackage = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gorm.GormFieldOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.gorm.GormFieldOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gorm.GormFieldOptions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gorm.GormFieldOptions.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gorm.GormFieldOptions}
 */
proto.gorm.GormFieldOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gorm.GormFieldOptions;
  return proto.gorm.GormFieldOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gorm.GormFieldOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gorm.GormFieldOptions}
 */
proto.gorm.GormFieldOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gorm.GormFieldOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gorm.GormFieldOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gorm.GormFieldOptions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gorm.GormFieldOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gorm.GormTag.prototype.toObject = function(opt_includeInstance) {
  return proto.gorm.GormTag.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gorm.GormTag} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gorm.GormTag.toObject = function(includeInstance, msg) {
  var f, obj = {
    column: jspb.Message.getFieldWithDefault(msg, 1, ""),
    type: jspb.Message.getFieldWithDefault(msg, 2, ""),
    size: jspb.Message.getFieldWithDefault(msg, 3, 0),
    primaryKey: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    unique: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    pb_default: jspb.Message.getFieldWithDefault(msg, 6, ""),
    precision: jspb.Message.getFieldWithDefault(msg, 7, ""),
    scale: jspb.Message.getFieldWithDefault(msg, 8, 0),
    notNull: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
    autoIncrement: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
    autoIncrementIncrement: jspb.Message.getFieldWithDefault(msg, 11, 0),
    embedded: jspb.Message.getBooleanFieldWithDefault(msg, 12, false),
    embeddedPrefix: jspb.Message.getFieldWithDefault(msg, 13, ""),
    autoCreateTime: jspb.Message.getBooleanFieldWithDefault(msg, 14, false),
    autoUpdateTime: jspb.Message.getBooleanFieldWithDefault(msg, 15, false),
    index: jspb.Message.getBooleanFieldWithDefault(msg, 16, false),
    uniqueIndex: jspb.Message.getBooleanFieldWithDefault(msg, 17, false),
    check: jspb.Message.getFieldWithDefault(msg, 18, ""),
    permission: jspb.Message.getFieldWithDefault(msg, 19, ""),
    comment: jspb.Message.getFieldWithDefault(msg, 20, ""),
    tags: jspb.Message.getFieldWithDefault(msg, 21, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gorm.GormTag}
 */
proto.gorm.GormTag.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gorm.GormTag;
  return proto.gorm.GormTag.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gorm.GormTag} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gorm.GormTag}
 */
proto.gorm.GormTag.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setColumn(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSize(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPrimaryKey(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setUnique(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDefault(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setPrecision(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setScale(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNotNull(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAutoIncrement(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAutoIncrementIncrement(value);
      break;
    case 12:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEmbedded(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmbeddedPrefix(value);
      break;
    case 14:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAutoCreateTime(value);
      break;
    case 15:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAutoUpdateTime(value);
      break;
    case 16:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIndex(value);
      break;
    case 17:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setUniqueIndex(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setCheck(value);
      break;
    case 19:
      var value = /** @type {string} */ (reader.readString());
      msg.setPermission(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.setComment(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.setTags(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gorm.GormTag.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gorm.GormTag.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gorm.GormTag} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gorm.GormTag.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getColumn();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSize();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getPrimaryKey();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getUnique();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getDefault();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getPrecision();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getScale();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getNotNull();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getAutoIncrement();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
  f = message.getAutoIncrementIncrement();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = message.getEmbedded();
  if (f) {
    writer.writeBool(
      12,
      f
    );
  }
  f = message.getEmbeddedPrefix();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getAutoCreateTime();
  if (f) {
    writer.writeBool(
      14,
      f
    );
  }
  f = message.getAutoUpdateTime();
  if (f) {
    writer.writeBool(
      15,
      f
    );
  }
  f = message.getIndex();
  if (f) {
    writer.writeBool(
      16,
      f
    );
  }
  f = message.getUniqueIndex();
  if (f) {
    writer.writeBool(
      17,
      f
    );
  }
  f = message.getCheck();
  if (f.length > 0) {
    writer.writeString(
      18,
      f
    );
  }
  f = message.getPermission();
  if (f.length > 0) {
    writer.writeString(
      19,
      f
    );
  }
  f = message.getComment();
  if (f.length > 0) {
    writer.writeString(
      20,
      f
    );
  }
  f = message.getTags();
  if (f.length > 0) {
    writer.writeString(
      21,
      f
    );
  }
};


/**
 * optional string column = 1;
 * @return {string}
 */
proto.gorm.GormTag.prototype.getColumn = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.GormTag} returns this
 */
proto.gorm.GormTag.prototype.setColumn = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string type = 2;
 * @return {string}
 */
proto.gorm.GormTag.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.GormTag} returns this
 */
proto.gorm.GormTag.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 size = 3;
 * @return {number}
 */
proto.gorm.GormTag.prototype.getSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.gorm.GormTag} returns this
 */
proto.gorm.GormTag.prototype.setSize = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional bool primary_key = 4;
 * @return {boolean}
 */
proto.gorm.GormTag.prototype.getPrimaryKey = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.GormTag} returns this
 */
proto.gorm.GormTag.prototype.setPrimaryKey = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool unique = 5;
 * @return {boolean}
 */
proto.gorm.GormTag.prototype.getUnique = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.GormTag} returns this
 */
proto.gorm.GormTag.prototype.setUnique = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional string default = 6;
 * @return {string}
 */
proto.gorm.GormTag.prototype.getDefault = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.GormTag} returns this
 */
proto.gorm.GormTag.prototype.setDefault = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string precision = 7;
 * @return {string}
 */
proto.gorm.GormTag.prototype.getPrecision = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.GormTag} returns this
 */
proto.gorm.GormTag.prototype.setPrecision = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional int32 scale = 8;
 * @return {number}
 */
proto.gorm.GormTag.prototype.getScale = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.gorm.GormTag} returns this
 */
proto.gorm.GormTag.prototype.setScale = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional bool not_null = 9;
 * @return {boolean}
 */
proto.gorm.GormTag.prototype.getNotNull = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.GormTag} returns this
 */
proto.gorm.GormTag.prototype.setNotNull = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional bool auto_increment = 10;
 * @return {boolean}
 */
proto.gorm.GormTag.prototype.getAutoIncrement = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.GormTag} returns this
 */
proto.gorm.GormTag.prototype.setAutoIncrement = function(value) {
  return jspb.Message.setProto3BooleanField(this, 10, value);
};


/**
 * optional int32 auto_increment_increment = 11;
 * @return {number}
 */
proto.gorm.GormTag.prototype.getAutoIncrementIncrement = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.gorm.GormTag} returns this
 */
proto.gorm.GormTag.prototype.setAutoIncrementIncrement = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional bool embedded = 12;
 * @return {boolean}
 */
proto.gorm.GormTag.prototype.getEmbedded = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 12, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.GormTag} returns this
 */
proto.gorm.GormTag.prototype.setEmbedded = function(value) {
  return jspb.Message.setProto3BooleanField(this, 12, value);
};


/**
 * optional string embedded_prefix = 13;
 * @return {string}
 */
proto.gorm.GormTag.prototype.getEmbeddedPrefix = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.GormTag} returns this
 */
proto.gorm.GormTag.prototype.setEmbeddedPrefix = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional bool auto_create_time = 14;
 * @return {boolean}
 */
proto.gorm.GormTag.prototype.getAutoCreateTime = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 14, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.GormTag} returns this
 */
proto.gorm.GormTag.prototype.setAutoCreateTime = function(value) {
  return jspb.Message.setProto3BooleanField(this, 14, value);
};


/**
 * optional bool auto_update_time = 15;
 * @return {boolean}
 */
proto.gorm.GormTag.prototype.getAutoUpdateTime = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 15, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.GormTag} returns this
 */
proto.gorm.GormTag.prototype.setAutoUpdateTime = function(value) {
  return jspb.Message.setProto3BooleanField(this, 15, value);
};


/**
 * optional bool index = 16;
 * @return {boolean}
 */
proto.gorm.GormTag.prototype.getIndex = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 16, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.GormTag} returns this
 */
proto.gorm.GormTag.prototype.setIndex = function(value) {
  return jspb.Message.setProto3BooleanField(this, 16, value);
};


/**
 * optional bool unique_index = 17;
 * @return {boolean}
 */
proto.gorm.GormTag.prototype.getUniqueIndex = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 17, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.GormTag} returns this
 */
proto.gorm.GormTag.prototype.setUniqueIndex = function(value) {
  return jspb.Message.setProto3BooleanField(this, 17, value);
};


/**
 * optional string check = 18;
 * @return {string}
 */
proto.gorm.GormTag.prototype.getCheck = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.GormTag} returns this
 */
proto.gorm.GormTag.prototype.setCheck = function(value) {
  return jspb.Message.setProto3StringField(this, 18, value);
};


/**
 * optional string permission = 19;
 * @return {string}
 */
proto.gorm.GormTag.prototype.getPermission = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 19, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.GormTag} returns this
 */
proto.gorm.GormTag.prototype.setPermission = function(value) {
  return jspb.Message.setProto3StringField(this, 19, value);
};


/**
 * optional string comment = 20;
 * @return {string}
 */
proto.gorm.GormTag.prototype.getComment = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 20, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.GormTag} returns this
 */
proto.gorm.GormTag.prototype.setComment = function(value) {
  return jspb.Message.setProto3StringField(this, 20, value);
};


/**
 * optional string tags = 21;
 * @return {string}
 */
proto.gorm.GormTag.prototype.getTags = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 21, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.GormTag} returns this
 */
proto.gorm.GormTag.prototype.setTags = function(value) {
  return jspb.Message.setProto3StringField(this, 21, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gorm.HasOneOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.gorm.HasOneOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gorm.HasOneOptions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gorm.HasOneOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    foreignkey: jspb.Message.getFieldWithDefault(msg, 1, ""),
    foreignkeyTag: (f = msg.getForeignkeyTag()) && proto.gorm.GormTag.toObject(includeInstance, f),
    associationForeignkey: jspb.Message.getFieldWithDefault(msg, 3, ""),
    associationAutoupdate: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    associationAutocreate: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    associationSaveReference: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    preload: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    replace: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    append: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
    clear: jspb.Message.getBooleanFieldWithDefault(msg, 10, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gorm.HasOneOptions}
 */
proto.gorm.HasOneOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gorm.HasOneOptions;
  return proto.gorm.HasOneOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gorm.HasOneOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gorm.HasOneOptions}
 */
proto.gorm.HasOneOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setForeignkey(value);
      break;
    case 2:
      var value = new proto.gorm.GormTag;
      reader.readMessage(value,proto.gorm.GormTag.deserializeBinaryFromReader);
      msg.setForeignkeyTag(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAssociationForeignkey(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAssociationAutoupdate(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAssociationAutocreate(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAssociationSaveReference(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPreload(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReplace(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAppend(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setClear(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gorm.HasOneOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gorm.HasOneOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gorm.HasOneOptions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gorm.HasOneOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getForeignkey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getForeignkeyTag();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.gorm.GormTag.serializeBinaryToWriter
    );
  }
  f = message.getAssociationForeignkey();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAssociationAutoupdate();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getAssociationAutocreate();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getAssociationSaveReference();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getPreload();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getReplace();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getAppend();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getClear();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
};


/**
 * optional string foreignkey = 1;
 * @return {string}
 */
proto.gorm.HasOneOptions.prototype.getForeignkey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.HasOneOptions} returns this
 */
proto.gorm.HasOneOptions.prototype.setForeignkey = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional GormTag foreignkey_tag = 2;
 * @return {?proto.gorm.GormTag}
 */
proto.gorm.HasOneOptions.prototype.getForeignkeyTag = function() {
  return /** @type{?proto.gorm.GormTag} */ (
    jspb.Message.getWrapperField(this, proto.gorm.GormTag, 2));
};


/**
 * @param {?proto.gorm.GormTag|undefined} value
 * @return {!proto.gorm.HasOneOptions} returns this
*/
proto.gorm.HasOneOptions.prototype.setForeignkeyTag = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gorm.HasOneOptions} returns this
 */
proto.gorm.HasOneOptions.prototype.clearForeignkeyTag = function() {
  return this.setForeignkeyTag(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gorm.HasOneOptions.prototype.hasForeignkeyTag = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string association_foreignkey = 3;
 * @return {string}
 */
proto.gorm.HasOneOptions.prototype.getAssociationForeignkey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.HasOneOptions} returns this
 */
proto.gorm.HasOneOptions.prototype.setAssociationForeignkey = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional bool association_autoupdate = 4;
 * @return {boolean}
 */
proto.gorm.HasOneOptions.prototype.getAssociationAutoupdate = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.HasOneOptions} returns this
 */
proto.gorm.HasOneOptions.prototype.setAssociationAutoupdate = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool association_autocreate = 5;
 * @return {boolean}
 */
proto.gorm.HasOneOptions.prototype.getAssociationAutocreate = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.HasOneOptions} returns this
 */
proto.gorm.HasOneOptions.prototype.setAssociationAutocreate = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool association_save_reference = 6;
 * @return {boolean}
 */
proto.gorm.HasOneOptions.prototype.getAssociationSaveReference = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.HasOneOptions} returns this
 */
proto.gorm.HasOneOptions.prototype.setAssociationSaveReference = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool preload = 7;
 * @return {boolean}
 */
proto.gorm.HasOneOptions.prototype.getPreload = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.HasOneOptions} returns this
 */
proto.gorm.HasOneOptions.prototype.setPreload = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional bool replace = 8;
 * @return {boolean}
 */
proto.gorm.HasOneOptions.prototype.getReplace = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.HasOneOptions} returns this
 */
proto.gorm.HasOneOptions.prototype.setReplace = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional bool append = 9;
 * @return {boolean}
 */
proto.gorm.HasOneOptions.prototype.getAppend = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.HasOneOptions} returns this
 */
proto.gorm.HasOneOptions.prototype.setAppend = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional bool clear = 10;
 * @return {boolean}
 */
proto.gorm.HasOneOptions.prototype.getClear = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.HasOneOptions} returns this
 */
proto.gorm.HasOneOptions.prototype.setClear = function(value) {
  return jspb.Message.setProto3BooleanField(this, 10, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gorm.BelongsToOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.gorm.BelongsToOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gorm.BelongsToOptions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gorm.BelongsToOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    foreignkey: jspb.Message.getFieldWithDefault(msg, 1, ""),
    foreignkeyTag: (f = msg.getForeignkeyTag()) && proto.gorm.GormTag.toObject(includeInstance, f),
    associationForeignkey: jspb.Message.getFieldWithDefault(msg, 3, ""),
    associationAutoupdate: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    associationAutocreate: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    associationSaveReference: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    preload: jspb.Message.getBooleanFieldWithDefault(msg, 7, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gorm.BelongsToOptions}
 */
proto.gorm.BelongsToOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gorm.BelongsToOptions;
  return proto.gorm.BelongsToOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gorm.BelongsToOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gorm.BelongsToOptions}
 */
proto.gorm.BelongsToOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setForeignkey(value);
      break;
    case 2:
      var value = new proto.gorm.GormTag;
      reader.readMessage(value,proto.gorm.GormTag.deserializeBinaryFromReader);
      msg.setForeignkeyTag(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAssociationForeignkey(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAssociationAutoupdate(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAssociationAutocreate(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAssociationSaveReference(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPreload(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gorm.BelongsToOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gorm.BelongsToOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gorm.BelongsToOptions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gorm.BelongsToOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getForeignkey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getForeignkeyTag();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.gorm.GormTag.serializeBinaryToWriter
    );
  }
  f = message.getAssociationForeignkey();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAssociationAutoupdate();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getAssociationAutocreate();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getAssociationSaveReference();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getPreload();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
};


/**
 * optional string foreignkey = 1;
 * @return {string}
 */
proto.gorm.BelongsToOptions.prototype.getForeignkey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.BelongsToOptions} returns this
 */
proto.gorm.BelongsToOptions.prototype.setForeignkey = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional GormTag foreignkey_tag = 2;
 * @return {?proto.gorm.GormTag}
 */
proto.gorm.BelongsToOptions.prototype.getForeignkeyTag = function() {
  return /** @type{?proto.gorm.GormTag} */ (
    jspb.Message.getWrapperField(this, proto.gorm.GormTag, 2));
};


/**
 * @param {?proto.gorm.GormTag|undefined} value
 * @return {!proto.gorm.BelongsToOptions} returns this
*/
proto.gorm.BelongsToOptions.prototype.setForeignkeyTag = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gorm.BelongsToOptions} returns this
 */
proto.gorm.BelongsToOptions.prototype.clearForeignkeyTag = function() {
  return this.setForeignkeyTag(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gorm.BelongsToOptions.prototype.hasForeignkeyTag = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string association_foreignkey = 3;
 * @return {string}
 */
proto.gorm.BelongsToOptions.prototype.getAssociationForeignkey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.BelongsToOptions} returns this
 */
proto.gorm.BelongsToOptions.prototype.setAssociationForeignkey = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional bool association_autoupdate = 4;
 * @return {boolean}
 */
proto.gorm.BelongsToOptions.prototype.getAssociationAutoupdate = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.BelongsToOptions} returns this
 */
proto.gorm.BelongsToOptions.prototype.setAssociationAutoupdate = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool association_autocreate = 5;
 * @return {boolean}
 */
proto.gorm.BelongsToOptions.prototype.getAssociationAutocreate = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.BelongsToOptions} returns this
 */
proto.gorm.BelongsToOptions.prototype.setAssociationAutocreate = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool association_save_reference = 6;
 * @return {boolean}
 */
proto.gorm.BelongsToOptions.prototype.getAssociationSaveReference = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.BelongsToOptions} returns this
 */
proto.gorm.BelongsToOptions.prototype.setAssociationSaveReference = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool preload = 7;
 * @return {boolean}
 */
proto.gorm.BelongsToOptions.prototype.getPreload = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.BelongsToOptions} returns this
 */
proto.gorm.BelongsToOptions.prototype.setPreload = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gorm.HasManyOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.gorm.HasManyOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gorm.HasManyOptions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gorm.HasManyOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    foreignkey: jspb.Message.getFieldWithDefault(msg, 1, ""),
    foreignkeyTag: (f = msg.getForeignkeyTag()) && proto.gorm.GormTag.toObject(includeInstance, f),
    associationForeignkey: jspb.Message.getFieldWithDefault(msg, 3, ""),
    positionField: jspb.Message.getFieldWithDefault(msg, 4, ""),
    positionFieldTag: (f = msg.getPositionFieldTag()) && proto.gorm.GormTag.toObject(includeInstance, f),
    associationAutoupdate: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    associationAutocreate: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    associationSaveReference: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    preload: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
    replace: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
    append: jspb.Message.getBooleanFieldWithDefault(msg, 11, false),
    clear: jspb.Message.getBooleanFieldWithDefault(msg, 12, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gorm.HasManyOptions}
 */
proto.gorm.HasManyOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gorm.HasManyOptions;
  return proto.gorm.HasManyOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gorm.HasManyOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gorm.HasManyOptions}
 */
proto.gorm.HasManyOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setForeignkey(value);
      break;
    case 2:
      var value = new proto.gorm.GormTag;
      reader.readMessage(value,proto.gorm.GormTag.deserializeBinaryFromReader);
      msg.setForeignkeyTag(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAssociationForeignkey(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPositionField(value);
      break;
    case 5:
      var value = new proto.gorm.GormTag;
      reader.readMessage(value,proto.gorm.GormTag.deserializeBinaryFromReader);
      msg.setPositionFieldTag(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAssociationAutoupdate(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAssociationAutocreate(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAssociationSaveReference(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPreload(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReplace(value);
      break;
    case 11:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAppend(value);
      break;
    case 12:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setClear(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gorm.HasManyOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gorm.HasManyOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gorm.HasManyOptions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gorm.HasManyOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getForeignkey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getForeignkeyTag();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.gorm.GormTag.serializeBinaryToWriter
    );
  }
  f = message.getAssociationForeignkey();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPositionField();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getPositionFieldTag();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.gorm.GormTag.serializeBinaryToWriter
    );
  }
  f = message.getAssociationAutoupdate();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getAssociationAutocreate();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getAssociationSaveReference();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getPreload();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getReplace();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
  f = message.getAppend();
  if (f) {
    writer.writeBool(
      11,
      f
    );
  }
  f = message.getClear();
  if (f) {
    writer.writeBool(
      12,
      f
    );
  }
};


/**
 * optional string foreignkey = 1;
 * @return {string}
 */
proto.gorm.HasManyOptions.prototype.getForeignkey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.HasManyOptions} returns this
 */
proto.gorm.HasManyOptions.prototype.setForeignkey = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional GormTag foreignkey_tag = 2;
 * @return {?proto.gorm.GormTag}
 */
proto.gorm.HasManyOptions.prototype.getForeignkeyTag = function() {
  return /** @type{?proto.gorm.GormTag} */ (
    jspb.Message.getWrapperField(this, proto.gorm.GormTag, 2));
};


/**
 * @param {?proto.gorm.GormTag|undefined} value
 * @return {!proto.gorm.HasManyOptions} returns this
*/
proto.gorm.HasManyOptions.prototype.setForeignkeyTag = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gorm.HasManyOptions} returns this
 */
proto.gorm.HasManyOptions.prototype.clearForeignkeyTag = function() {
  return this.setForeignkeyTag(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gorm.HasManyOptions.prototype.hasForeignkeyTag = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string association_foreignkey = 3;
 * @return {string}
 */
proto.gorm.HasManyOptions.prototype.getAssociationForeignkey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.HasManyOptions} returns this
 */
proto.gorm.HasManyOptions.prototype.setAssociationForeignkey = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string position_field = 4;
 * @return {string}
 */
proto.gorm.HasManyOptions.prototype.getPositionField = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.HasManyOptions} returns this
 */
proto.gorm.HasManyOptions.prototype.setPositionField = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional GormTag position_field_tag = 5;
 * @return {?proto.gorm.GormTag}
 */
proto.gorm.HasManyOptions.prototype.getPositionFieldTag = function() {
  return /** @type{?proto.gorm.GormTag} */ (
    jspb.Message.getWrapperField(this, proto.gorm.GormTag, 5));
};


/**
 * @param {?proto.gorm.GormTag|undefined} value
 * @return {!proto.gorm.HasManyOptions} returns this
*/
proto.gorm.HasManyOptions.prototype.setPositionFieldTag = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gorm.HasManyOptions} returns this
 */
proto.gorm.HasManyOptions.prototype.clearPositionFieldTag = function() {
  return this.setPositionFieldTag(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gorm.HasManyOptions.prototype.hasPositionFieldTag = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional bool association_autoupdate = 6;
 * @return {boolean}
 */
proto.gorm.HasManyOptions.prototype.getAssociationAutoupdate = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.HasManyOptions} returns this
 */
proto.gorm.HasManyOptions.prototype.setAssociationAutoupdate = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool association_autocreate = 7;
 * @return {boolean}
 */
proto.gorm.HasManyOptions.prototype.getAssociationAutocreate = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.HasManyOptions} returns this
 */
proto.gorm.HasManyOptions.prototype.setAssociationAutocreate = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional bool association_save_reference = 8;
 * @return {boolean}
 */
proto.gorm.HasManyOptions.prototype.getAssociationSaveReference = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.HasManyOptions} returns this
 */
proto.gorm.HasManyOptions.prototype.setAssociationSaveReference = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional bool preload = 9;
 * @return {boolean}
 */
proto.gorm.HasManyOptions.prototype.getPreload = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.HasManyOptions} returns this
 */
proto.gorm.HasManyOptions.prototype.setPreload = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional bool replace = 10;
 * @return {boolean}
 */
proto.gorm.HasManyOptions.prototype.getReplace = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.HasManyOptions} returns this
 */
proto.gorm.HasManyOptions.prototype.setReplace = function(value) {
  return jspb.Message.setProto3BooleanField(this, 10, value);
};


/**
 * optional bool append = 11;
 * @return {boolean}
 */
proto.gorm.HasManyOptions.prototype.getAppend = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 11, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.HasManyOptions} returns this
 */
proto.gorm.HasManyOptions.prototype.setAppend = function(value) {
  return jspb.Message.setProto3BooleanField(this, 11, value);
};


/**
 * optional bool clear = 12;
 * @return {boolean}
 */
proto.gorm.HasManyOptions.prototype.getClear = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 12, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.HasManyOptions} returns this
 */
proto.gorm.HasManyOptions.prototype.setClear = function(value) {
  return jspb.Message.setProto3BooleanField(this, 12, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gorm.ManyToManyOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.gorm.ManyToManyOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gorm.ManyToManyOptions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gorm.ManyToManyOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    jointable: jspb.Message.getFieldWithDefault(msg, 1, ""),
    foreignkey: jspb.Message.getFieldWithDefault(msg, 2, ""),
    jointableForeignkey: jspb.Message.getFieldWithDefault(msg, 3, ""),
    associationForeignkey: jspb.Message.getFieldWithDefault(msg, 4, ""),
    associationJointableForeignkey: jspb.Message.getFieldWithDefault(msg, 5, ""),
    associationAutoupdate: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    associationAutocreate: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    associationSaveReference: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    preload: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
    replace: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
    append: jspb.Message.getBooleanFieldWithDefault(msg, 11, false),
    clear: jspb.Message.getBooleanFieldWithDefault(msg, 13, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gorm.ManyToManyOptions}
 */
proto.gorm.ManyToManyOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gorm.ManyToManyOptions;
  return proto.gorm.ManyToManyOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gorm.ManyToManyOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gorm.ManyToManyOptions}
 */
proto.gorm.ManyToManyOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setJointable(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setForeignkey(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setJointableForeignkey(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setAssociationForeignkey(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setAssociationJointableForeignkey(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAssociationAutoupdate(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAssociationAutocreate(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAssociationSaveReference(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPreload(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReplace(value);
      break;
    case 11:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAppend(value);
      break;
    case 13:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setClear(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gorm.ManyToManyOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gorm.ManyToManyOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gorm.ManyToManyOptions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gorm.ManyToManyOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getJointable();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getForeignkey();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getJointableForeignkey();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAssociationForeignkey();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getAssociationJointableForeignkey();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getAssociationAutoupdate();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getAssociationAutocreate();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getAssociationSaveReference();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getPreload();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getReplace();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
  f = message.getAppend();
  if (f) {
    writer.writeBool(
      11,
      f
    );
  }
  f = message.getClear();
  if (f) {
    writer.writeBool(
      13,
      f
    );
  }
};


/**
 * optional string jointable = 1;
 * @return {string}
 */
proto.gorm.ManyToManyOptions.prototype.getJointable = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.ManyToManyOptions} returns this
 */
proto.gorm.ManyToManyOptions.prototype.setJointable = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string foreignkey = 2;
 * @return {string}
 */
proto.gorm.ManyToManyOptions.prototype.getForeignkey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.ManyToManyOptions} returns this
 */
proto.gorm.ManyToManyOptions.prototype.setForeignkey = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string jointable_foreignkey = 3;
 * @return {string}
 */
proto.gorm.ManyToManyOptions.prototype.getJointableForeignkey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.ManyToManyOptions} returns this
 */
proto.gorm.ManyToManyOptions.prototype.setJointableForeignkey = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string association_foreignkey = 4;
 * @return {string}
 */
proto.gorm.ManyToManyOptions.prototype.getAssociationForeignkey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.ManyToManyOptions} returns this
 */
proto.gorm.ManyToManyOptions.prototype.setAssociationForeignkey = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string association_jointable_foreignkey = 5;
 * @return {string}
 */
proto.gorm.ManyToManyOptions.prototype.getAssociationJointableForeignkey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.ManyToManyOptions} returns this
 */
proto.gorm.ManyToManyOptions.prototype.setAssociationJointableForeignkey = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional bool association_autoupdate = 6;
 * @return {boolean}
 */
proto.gorm.ManyToManyOptions.prototype.getAssociationAutoupdate = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.ManyToManyOptions} returns this
 */
proto.gorm.ManyToManyOptions.prototype.setAssociationAutoupdate = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool association_autocreate = 7;
 * @return {boolean}
 */
proto.gorm.ManyToManyOptions.prototype.getAssociationAutocreate = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.ManyToManyOptions} returns this
 */
proto.gorm.ManyToManyOptions.prototype.setAssociationAutocreate = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional bool association_save_reference = 8;
 * @return {boolean}
 */
proto.gorm.ManyToManyOptions.prototype.getAssociationSaveReference = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.ManyToManyOptions} returns this
 */
proto.gorm.ManyToManyOptions.prototype.setAssociationSaveReference = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional bool preload = 9;
 * @return {boolean}
 */
proto.gorm.ManyToManyOptions.prototype.getPreload = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.ManyToManyOptions} returns this
 */
proto.gorm.ManyToManyOptions.prototype.setPreload = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional bool replace = 10;
 * @return {boolean}
 */
proto.gorm.ManyToManyOptions.prototype.getReplace = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.ManyToManyOptions} returns this
 */
proto.gorm.ManyToManyOptions.prototype.setReplace = function(value) {
  return jspb.Message.setProto3BooleanField(this, 10, value);
};


/**
 * optional bool append = 11;
 * @return {boolean}
 */
proto.gorm.ManyToManyOptions.prototype.getAppend = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 11, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.ManyToManyOptions} returns this
 */
proto.gorm.ManyToManyOptions.prototype.setAppend = function(value) {
  return jspb.Message.setProto3BooleanField(this, 11, value);
};


/**
 * optional bool clear = 13;
 * @return {boolean}
 */
proto.gorm.ManyToManyOptions.prototype.getClear = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 13, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.ManyToManyOptions} returns this
 */
proto.gorm.ManyToManyOptions.prototype.setClear = function(value) {
  return jspb.Message.setProto3BooleanField(this, 13, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gorm.AutoServerOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.gorm.AutoServerOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gorm.AutoServerOptions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gorm.AutoServerOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    autogen: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    txnMiddleware: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    withTracing: jspb.Message.getBooleanFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gorm.AutoServerOptions}
 */
proto.gorm.AutoServerOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gorm.AutoServerOptions;
  return proto.gorm.AutoServerOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gorm.AutoServerOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gorm.AutoServerOptions}
 */
proto.gorm.AutoServerOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAutogen(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTxnMiddleware(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setWithTracing(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gorm.AutoServerOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gorm.AutoServerOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gorm.AutoServerOptions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gorm.AutoServerOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAutogen();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getTxnMiddleware();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getWithTracing();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * optional bool autogen = 1;
 * @return {boolean}
 */
proto.gorm.AutoServerOptions.prototype.getAutogen = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.AutoServerOptions} returns this
 */
proto.gorm.AutoServerOptions.prototype.setAutogen = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional bool txn_middleware = 2;
 * @return {boolean}
 */
proto.gorm.AutoServerOptions.prototype.getTxnMiddleware = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.AutoServerOptions} returns this
 */
proto.gorm.AutoServerOptions.prototype.setTxnMiddleware = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool with_tracing = 3;
 * @return {boolean}
 */
proto.gorm.AutoServerOptions.prototype.getWithTracing = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gorm.AutoServerOptions} returns this
 */
proto.gorm.AutoServerOptions.prototype.setWithTracing = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gorm.MethodOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.gorm.MethodOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gorm.MethodOptions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gorm.MethodOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    objectType: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gorm.MethodOptions}
 */
proto.gorm.MethodOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gorm.MethodOptions;
  return proto.gorm.MethodOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gorm.MethodOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gorm.MethodOptions}
 */
proto.gorm.MethodOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setObjectType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gorm.MethodOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gorm.MethodOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gorm.MethodOptions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gorm.MethodOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getObjectType();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string object_type = 1;
 * @return {string}
 */
proto.gorm.MethodOptions.prototype.getObjectType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.MethodOptions} returns this
 */
proto.gorm.MethodOptions.prototype.setObjectType = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * A tuple of {field number, class constructor} for the extension
 * field named `tablePrefix`.
 * @type {!jspb.ExtensionFieldInfo<string>}
 */
proto.gorm.tablePrefix = new jspb.ExtensionFieldInfo(
    1018,
    {tablePrefix: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

google_protobuf_descriptor_pb.FileOptions.extensionsBinary[1018] = new jspb.ExtensionFieldBinaryInfo(
    proto.gorm.tablePrefix,
    jspb.BinaryReader.prototype.readString,
    jspb.BinaryWriter.prototype.writeString,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.FileOptions.extensions[1018] = proto.gorm.tablePrefix;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `ormable`.
 * @type {!jspb.ExtensionFieldInfo<boolean>}
 */
proto.gorm.ormable = new jspb.ExtensionFieldInfo(
    1018,
    {ormable: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

google_protobuf_descriptor_pb.MessageOptions.extensionsBinary[1018] = new jspb.ExtensionFieldBinaryInfo(
    proto.gorm.ormable,
    jspb.BinaryReader.prototype.readBool,
    jspb.BinaryWriter.prototype.writeBool,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MessageOptions.extensions[1018] = proto.gorm.ormable;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `includeList`.
 * @type {!jspb.ExtensionFieldInfo<!Array<!proto.gorm.ExtraField>>}
 */
proto.gorm.includeList = new jspb.ExtensionFieldInfo(
    1019,
    {includeList: 0},
    proto.gorm.ExtraField,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.gorm.ExtraField.toObject),
    1);

google_protobuf_descriptor_pb.MessageOptions.extensionsBinary[1019] = new jspb.ExtensionFieldBinaryInfo(
    proto.gorm.includeList,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeRepeatedMessage,
    proto.gorm.ExtraField.serializeBinaryToWriter,
    proto.gorm.ExtraField.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MessageOptions.extensions[1019] = proto.gorm.includeList;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `table`.
 * @type {!jspb.ExtensionFieldInfo<string>}
 */
proto.gorm.table = new jspb.ExtensionFieldInfo(
    1020,
    {table: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

google_protobuf_descriptor_pb.MessageOptions.extensionsBinary[1020] = new jspb.ExtensionFieldBinaryInfo(
    proto.gorm.table,
    jspb.BinaryReader.prototype.readString,
    jspb.BinaryWriter.prototype.writeString,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MessageOptions.extensions[1020] = proto.gorm.table;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `tag`.
 * @type {!jspb.ExtensionFieldInfo<string>}
 */
proto.gorm.tag = new jspb.ExtensionFieldInfo(
    1018,
    {tag: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

google_protobuf_descriptor_pb.FieldOptions.extensionsBinary[1018] = new jspb.ExtensionFieldBinaryInfo(
    proto.gorm.tag,
    jspb.BinaryReader.prototype.readString,
    jspb.BinaryWriter.prototype.writeString,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.FieldOptions.extensions[1018] = proto.gorm.tag;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `drop`.
 * @type {!jspb.ExtensionFieldInfo<boolean>}
 */
proto.gorm.drop = new jspb.ExtensionFieldInfo(
    1019,
    {drop: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

google_protobuf_descriptor_pb.FieldOptions.extensionsBinary[1019] = new jspb.ExtensionFieldBinaryInfo(
    proto.gorm.drop,
    jspb.BinaryReader.prototype.readBool,
    jspb.BinaryWriter.prototype.writeBool,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.FieldOptions.extensions[1019] = proto.gorm.drop;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `server`.
 * @type {!jspb.ExtensionFieldInfo<!proto.gorm.AutoServerOptions>}
 */
proto.gorm.server = new jspb.ExtensionFieldInfo(
    52119,
    {server: 0},
    proto.gorm.AutoServerOptions,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.gorm.AutoServerOptions.toObject),
    0);

google_protobuf_descriptor_pb.ServiceOptions.extensionsBinary[52119] = new jspb.ExtensionFieldBinaryInfo(
    proto.gorm.server,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.gorm.AutoServerOptions.serializeBinaryToWriter,
    proto.gorm.AutoServerOptions.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.ServiceOptions.extensions[52119] = proto.gorm.server;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `method`.
 * @type {!jspb.ExtensionFieldInfo<!proto.gorm.MethodOptions>}
 */
proto.gorm.method = new jspb.ExtensionFieldInfo(
    52119,
    {method: 0},
    proto.gorm.MethodOptions,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.gorm.MethodOptions.toObject),
    0);

google_protobuf_descriptor_pb.MethodOptions.extensionsBinary[52119] = new jspb.ExtensionFieldBinaryInfo(
    proto.gorm.method,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.gorm.MethodOptions.serializeBinaryToWriter,
    proto.gorm.MethodOptions.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MethodOptions.extensions[52119] = proto.gorm.method;

goog.object.extend(exports, proto.gorm);
