// source: options/gorm.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_descriptor_pb = require('google-protobuf/google/protobuf/descriptor_pb.js');
goog.object.extend(proto, google_protobuf_descriptor_pb);
goog.exportSymbol('proto.gorm.ExtraField', null, global);
goog.exportSymbol('proto.gorm.autogen', null, global);
goog.exportSymbol('proto.gorm.drop', null, global);
goog.exportSymbol('proto.gorm.includeList', null, global);
goog.exportSymbol('proto.gorm.ormable', null, global);
goog.exportSymbol('proto.gorm.table', null, global);
goog.exportSymbol('proto.gorm.tablePrefix', null, global);
goog.exportSymbol('proto.gorm.tag', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gorm.ExtraField = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gorm.ExtraField, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gorm.ExtraField.displayName = 'proto.gorm.ExtraField';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gorm.ExtraField.prototype.toObject = function(opt_includeInstance) {
  return proto.gorm.ExtraField.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gorm.ExtraField} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gorm.ExtraField.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    tag: jspb.Message.getFieldWithDefault(msg, 3, ""),
    pb_package: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gorm.ExtraField}
 */
proto.gorm.ExtraField.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gorm.ExtraField;
  return proto.gorm.ExtraField.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gorm.ExtraField} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gorm.ExtraField}
 */
proto.gorm.ExtraField.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTag(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPackage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gorm.ExtraField.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gorm.ExtraField.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gorm.ExtraField} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gorm.ExtraField.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTag();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPackage();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string type = 1;
 * @return {string}
 */
proto.gorm.ExtraField.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.ExtraField} returns this
 */
proto.gorm.ExtraField.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.gorm.ExtraField.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.ExtraField} returns this
 */
proto.gorm.ExtraField.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string tag = 3;
 * @return {string}
 */
proto.gorm.ExtraField.prototype.getTag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.ExtraField} returns this
 */
proto.gorm.ExtraField.prototype.setTag = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string package = 4;
 * @return {string}
 */
proto.gorm.ExtraField.prototype.getPackage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.gorm.ExtraField} returns this
 */
proto.gorm.ExtraField.prototype.setPackage = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};



/**
 * A tuple of {field number, class constructor} for the extension
 * field named `tablePrefix`.
 * @type {!jspb.ExtensionFieldInfo<string>}
 */
proto.gorm.tablePrefix = new jspb.ExtensionFieldInfo(
    1018,
    {tablePrefix: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

google_protobuf_descriptor_pb.FileOptions.extensionsBinary[1018] = new jspb.ExtensionFieldBinaryInfo(
    proto.gorm.tablePrefix,
    jspb.BinaryReader.prototype.readString,
    jspb.BinaryWriter.prototype.writeString,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.FileOptions.extensions[1018] = proto.gorm.tablePrefix;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `ormable`.
 * @type {!jspb.ExtensionFieldInfo<boolean>}
 */
proto.gorm.ormable = new jspb.ExtensionFieldInfo(
    1018,
    {ormable: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

google_protobuf_descriptor_pb.MessageOptions.extensionsBinary[1018] = new jspb.ExtensionFieldBinaryInfo(
    proto.gorm.ormable,
    jspb.BinaryReader.prototype.readBool,
    jspb.BinaryWriter.prototype.writeBool,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MessageOptions.extensions[1018] = proto.gorm.ormable;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `includeList`.
 * @type {!jspb.ExtensionFieldInfo<!Array<!proto.gorm.ExtraField>>}
 */
proto.gorm.includeList = new jspb.ExtensionFieldInfo(
    1019,
    {includeList: 0},
    proto.gorm.ExtraField,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.gorm.ExtraField.toObject),
    1);

google_protobuf_descriptor_pb.MessageOptions.extensionsBinary[1019] = new jspb.ExtensionFieldBinaryInfo(
    proto.gorm.includeList,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeRepeatedMessage,
    proto.gorm.ExtraField.serializeBinaryToWriter,
    proto.gorm.ExtraField.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MessageOptions.extensions[1019] = proto.gorm.includeList;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `table`.
 * @type {!jspb.ExtensionFieldInfo<string>}
 */
proto.gorm.table = new jspb.ExtensionFieldInfo(
    1020,
    {table: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

google_protobuf_descriptor_pb.MessageOptions.extensionsBinary[1020] = new jspb.ExtensionFieldBinaryInfo(
    proto.gorm.table,
    jspb.BinaryReader.prototype.readString,
    jspb.BinaryWriter.prototype.writeString,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MessageOptions.extensions[1020] = proto.gorm.table;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `tag`.
 * @type {!jspb.ExtensionFieldInfo<string>}
 */
proto.gorm.tag = new jspb.ExtensionFieldInfo(
    1018,
    {tag: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

google_protobuf_descriptor_pb.FieldOptions.extensionsBinary[1018] = new jspb.ExtensionFieldBinaryInfo(
    proto.gorm.tag,
    jspb.BinaryReader.prototype.readString,
    jspb.BinaryWriter.prototype.writeString,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.FieldOptions.extensions[1018] = proto.gorm.tag;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `drop`.
 * @type {!jspb.ExtensionFieldInfo<boolean>}
 */
proto.gorm.drop = new jspb.ExtensionFieldInfo(
    1019,
    {drop: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

google_protobuf_descriptor_pb.FieldOptions.extensionsBinary[1019] = new jspb.ExtensionFieldBinaryInfo(
    proto.gorm.drop,
    jspb.BinaryReader.prototype.readBool,
    jspb.BinaryWriter.prototype.writeBool,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.FieldOptions.extensions[1019] = proto.gorm.drop;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `autogen`.
 * @type {!jspb.ExtensionFieldInfo<boolean>}
 */
proto.gorm.autogen = new jspb.ExtensionFieldInfo(
    1018,
    {autogen: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

google_protobuf_descriptor_pb.ServiceOptions.extensionsBinary[1018] = new jspb.ExtensionFieldBinaryInfo(
    proto.gorm.autogen,
    jspb.BinaryReader.prototype.readBool,
    jspb.BinaryWriter.prototype.writeBool,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.ServiceOptions.extensions[1018] = proto.gorm.autogen;

goog.object.extend(exports, proto.gorm);
